### ISSUE TITLE
Adding a square to a project

### ISSUE THREAD

**Issue by SarahSaxifrage** [BiologicalRecordsCentre/plantportal#72] opened 2023-02-27 14:30 UTC
@andrewvanbreda @sacrevert 
When clicking on 'add square' the page auto redirects to the homepage rather than performing the action requested.

**Comment by andrewvanbreda** [comment] 2023-02-27 15:51
Hi @SarahSaxifrage @sacrevert 
Apologies.
This failure was caused by large changes occuring behind the scenes of the site recently that may not be visible to the user, the Add Square page is now actually a new page that this button wasn't pointing at.
(These changes relate to project managers now having correct control of projects, whereby previously only Plant Portal Website Administrators had rights to do things like edit squares they hadn't created)
Fixed now

**Closed as completed** 2023-02-27 15:54 UTC
Labels: Coding complete
